### ISSUE TITLE
反馈点问题

### ISSUE THREAD

**Issue by hausir** [eshengsky/jquery-emojis#1]
现在有用户了有Star了, 能添加点功能顺便把bug修复下不...
- 表情图片大小对显示效果有影响
- 按钮的定位方式对表情弹出位置有影响
- flag左右两边能不能不一样
- 后缀只能是数字, 希望支持自定义
- 中间的分界符只能是_, 希望支持自定义

**Comment by eshengsky** [comment]
@kuanger 年后有点忙，等闲下来会看下这几个问题。
也欢迎你贡献代码:smile:

**Comment by hausir** [comment]
@eshengsky 我给公司用上了:laughing:  很多问题 我有空的话肯定会贡献代码的

**Comment by eshengsky** [comment]
@kuanger 除了第2个弹出位置的问题，其它都做了一些处理 :smile:

**Comment by hausir** [comment]
@eshengsky 感谢，有空我升级下插件，最近公司有点小忙，项目貌似Star又增加了

**Comment by hausir** [comment]
@eshengsky www.weifengke.com 用在这里了 发帖和回帖
