### ISSUE TITLE
Path: dist/img/qq

### ISSUE THREAD

**Issue by markelvu1** [eshengsky/jquery-emojis#10]
It works when it is dist/img/qq but if I cut the dist folder and move it into src folder, it doesn't work.

 Like I would src/dist/img/qq; the path is not recognized. Or even tried ./dist/img/qq or ../dist/img/qq or /src/dist/img/qq ; the path is not recognized.

The purpose is I am trying to implement it into Visual Studio but can't get  the path to recognize the filepath.

Like this emoji but can't get it to work when trying to implement it into my project. Please help!
Thanks in advance.

**Comment by eshengsky** [comment]
@markelvu1 Should be `src/dist/img/qq/` instead of `src/dist/img/qq`, thank you!

**Comment by markelvu1** [comment]
It works! Thank you!!!
