### ISSUE TITLE
Preload picture will stop emojiParse from working correctly 

### ISSUE THREAD

**Issue by markelvu1** [eshengsky/jquery-emojis#11]
When I load a picture file like  >img src="data:image/jpq; base64, some base64data file here" /< then have several emoji like >span :hehe: :haha:  /span<. It won't load the emojiParse correctly.

Sorry had to use >< rather than the correct way since it filter out.

Please help.

Thanks in advance!!

**Comment by eshengsky** [comment]
@markelvu1 It's not working if you insert img with base64, that's because your emoji placeholder (such as :laugh:) includes char ':', and the base64 string includes it too. I suggest you to change your emoji placeholder to another special, like '#laugh#'.

**Comment by markelvu1** [comment]
Thank you!!! It makes sense! I went around it by having the following and it seems to work. 
I would have >img src="data:image/jpq; base64, some base64data file here" /< and then an empty >img src="data:image/jpq; base64," width: 0 height: 0 /< and it seems to work everytime. Thanks for the quick response. Now I have another issues. Will post another issues on next post.
