### ISSUE TITLE
可编辑的div editable 粘贴富文本时带有格式，需要处理下

### ISSUE THREAD

**Issue by liujsim** [eshengsky/jquery-emojis#2]
[Javascript trick for 'paste as plain text` in execCommand](http://stackoverflow.com/questions/12027137/javascript-trick-for-paste-as-plain-text-in-execcommand)

[demo](http://jsfiddle.net/HBEzc/)

**Comment by eshengsky** [comment]
@runcelim 你应该需要自己处理paste事件，因为这不属于插件的职责，而且每个人的需求不一样——有的人可能就想要粘贴时保留原来的格式。
