### ISSUE TITLE
在 IE8 下运行错误, 代码有点小 bug

### ISSUE THREAD

**Issue by thinkbase** [eshengsky/jquery-emojis#4]
_insertAtCursor() 方法中 `else if ((sel = document.selection) && sel.type !== 'Control') {` 这个分支中 `sel.createRange().pasteHTML(html);` 应该是 `sel.createRange().pasteHTML(value);`, _insertAtCursor 方法没有 "html" 这个参数.

**Comment by eshengsky** [comment]
感谢，会在新版本中修复。
